# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PAT_KEY }} | docker login -u "redblackbird" --password-stdin

      - name: push docker
        run: |
             docker build -t "redblackbird/wififorge:latest" .
             docker push redblackbird/wififorge:latest
  
      - name: logout
        run: docker logout
